# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "PROJECTS" ("NAME" VARCHAR NOT NULL,"ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY);
create table "PROJECTS_MEMBERS" ("USER_ID" INTEGER,"PROJECT_ID" INTEGER);
create table "USERS" ("EMAIL" VARCHAR NOT NULL,"PASSWORD" VARCHAR NOT NULL,"ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY);
alter table "PROJECTS_MEMBERS" add constraint "USER_FK" foreign key("USER_ID") references "USERS"("ID") on update NO ACTION on delete NO ACTION;
alter table "PROJECTS_MEMBERS" add constraint "PROJECT_FK" foreign key("PROJECT_ID") references "PROJECTS"("ID") on update NO ACTION on delete NO ACTION;

# --- !Downs

alter table "PROJECTS_MEMBERS" drop constraint "USER_FK";
alter table "PROJECTS_MEMBERS" drop constraint "PROJECT_FK";
drop table "PROJECTS";
drop table "PROJECTS_MEMBERS";
drop table "USERS";

